---
# This ensures that keepalived is started

- name: Verify
  hosts: all[0]
  order: sorted
  gather_facts: yes
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Show ansible facts for keepalived
      ansible.builtin.debug:
        var: ansible_facts.services
        verbosity: 3

    - name: Ensure keepalived is started
      ansible.builtin.assert:
        that:
          - "ansible_facts.services['keepalived.service']['state'] == 'running'"
          - "ansible_facts.services['keepalived.service']['status'] == 'enabled'"
