---
- name: Cleanup default molecule scenario
  hosts: all[0]
  gather_facts: no
  tasks:
  - name: Create a network with custom IPAM config
    delegate_to: localhost
    community.docker.docker_network:
      name: keepalived-network
      state: absent
