---
lint: |
  set -e
  yamllint .
  ansible-lint -v --exclude=.tox
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: ansible
provisioner:
  name: ansible
  options:
    v: True
  log: True
platforms:
  - name: keepalived-rockylinux8
    pre_build_image: yes
    image: geerlingguy/docker-rockylinux8-ansible:latest
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: keepalived-bullseye
    pre_build_image: yes
    image: geerlingguy/docker-debian11-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    service_manager: systemd

  - name: keepalived-xenial
    pre_build_image: yes
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    service_manager: systemd

  - name: keepalived-bionic
    pre_build_image: yes
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: keepalived-focal
    pre_build_image: yes
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
