---
- name: Cleanup molecule masked-keepalived scenario
  hosts: all[0]
  gather_facts: no
  tasks:
  - name: Remove masked keepalived docker network
    delegate_to: localhost
    community.docker.docker_network:
      name: masked-keepalived-network
      state: absent
